# Generated by Django 5.0.1 on 2025-12-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icône"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0DE1E7", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Catégorie de service",
                "verbose_name_plural": "Catégories de services",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "short_description",
                    models.TextField(verbose_name="Description courte"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Description complète"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icône"),
                ),
                (
                    "price_starting_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix à partir de",
                    ),
                ),
                (
                    "duration",
                    models.CharField(blank=True, max_length=50, verbose_name="Durée"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Actif"), ("inactive", "Inactif")],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="services.servicecategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code (ex: ISO 9001)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certifications/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="services.servicecategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date limite"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de complétion"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de service",
                "verbose_name_plural": "Demandes de services",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(upload_to="deliverables/", verbose_name="Fichier"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_deliverables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploadé par",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="services.servicerequest",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livrable",
                "verbose_name_plural": "Livrables",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nom du client"),
                ),
                (
                    "client_position",
                    models.CharField(blank=True, max_length=200, verbose_name="Poste"),
                ),
                (
                    "client_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Entreprise"
                    ),
                ),
                (
                    "client_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Photo",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                ("rating", models.IntegerField(default=5, verbose_name="Note (1-5)")),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
